"""DPO (Direct Preference Optimization) training script.

Uses TRL's DPOTrainer to fine-tune the LoRA-adapted Qwen2.5-7B model
using reward-ranked strategy pairs generated by the RL feedback loop.

DPO directly optimizes the policy from preference data without needing
a separate reward model — the backtest reward serves as the ground truth.

Usage:
    python training/scripts/train_dpo.py \
        --model /workspace/persistent/qwen-trader-merged \
        --data training/data/processed/dpo_train.jsonl \
        --output /workspace/persistent/qwen-trader-dpo

Environment:
    Must run on AMD ROCm GPU instance.
    ROCm PyTorch + TRL + PEFT required.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def parse_args():
    parser = argparse.ArgumentParser(description="DPO training for trading agent")
    parser.add_argument("--model", default="Qwen/Qwen2.5-7B-Instruct",
                        help="Base model path or HuggingFace ID")
    parser.add_argument("--data", default=str(PROJECT_ROOT / "training/data/processed/dpo_train.jsonl"),
                        help="DPO training data JSONL path")
    parser.add_argument("--output", default="/workspace/persistent/qwen-trader-dpo",
                        help="Output directory for DPO adapter")
    parser.add_argument("--lora_r", type=int, default=16, help="LoRA rank")
    parser.add_argument("--lora_alpha", type=int, default=32, help="LoRA alpha")
    parser.add_argument("--lr", type=float, default=5e-6, help="Learning rate")
    parser.add_argument("--epochs", type=int, default=1, help="Training epochs")
    parser.add_argument("--batch_size", type=int, default=2, help="Batch size")
    parser.add_argument("--grad_accum", type=int, default=4, help="Gradient accumulation")
    return parser.parse_args()


def load_dpo_dataset(file_path: str):
    """Load DPO pairs from JSONL file."""
    data = []
    with open(file_path) as f:
        for line in f:
            entry = json.loads(line.strip())
            data.append({
                "prompt": entry["prompt"],
                "chosen": entry["chosen"],
                "rejected": entry["rejected"],
            })
    return data


def main():
    args = parse_args()

    # ── Environment (ROCm) ─────────────────────────────────────
    os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
    os.environ.setdefault("ROCBLAS_USE_HIPBLASLT", "1")

    # ── Imports (deferred for --help) ─────────────────────────
    import torch
    from datasets import Dataset
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import LoraConfig, get_peft_model
    from trl import DPOTrainer, DPOConfig

    print(f"PyTorch: {torch.__version__}")
    print(f"HIP available: {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")

    # ── Load model ─────────────────────────────────────────────
    print(f"\nLoading model: {args.model}")
    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True,
    )

    # ── LoRA config ────────────────────────────────────────────
    lora_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_dropout=0.05,
        task_type="CAUSAL_LM",
    )

    # ── Load DPO dataset ────────────────────────────────────────
    print(f"\nLoading DPO data: {args.data}")
    raw_data = load_dpo_dataset(args.data)
    print(f"  {len(raw_data)} preference pairs loaded")

    dataset = Dataset.from_list(raw_data)

    # ── DPO config ─────────────────────────────────────────────
    dpo_config = DPOConfig(
        output_dir=args.output,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        warmup_ratio=0.03,
        lr_scheduler_type="cosine",
        logging_steps=10,
        save_steps=50,
        bf16=True,
        gradient_checkpointing=True,
        max_length=2048,
        max_prompt_length=512,
        beta=0.1,  # DPO temperature
    )

    # ── Train ──────────────────────────────────────────────────
    trainer = DPOTrainer(
        model=model,
        args=dpo_config,
        train_dataset=dataset,
        processing_class=tokenizer,
        peft_config=lora_config,
    )

    print("\nStarting DPO training...")
    trainer.train()

    # ── Save ────────────────────────────────────────────────────
    trainer.save_model(f"{args.output}/final")
    tokenizer.save_pretrained(f"{args.output}/final")
    print(f"\n✅ DPO model saved to {args.output}/final")
    print("\nTo serve with vLLM:")
    print(f"  1. Merge LoRA: python training/scripts/merge_lora.py --base {args.model} --adapter {args.output}/final --output {args.output}/merged")
    print(f"  2. Serve: vllm serve {args.output}/merged --dtype bfloat16")


if __name__ == "__main__":
    main()
