"""集中调参 — 所有 3v3 比赛参数在这里调。

参考 Booster 官方基线 param.py，适配 Genesis + T1 机器人。
"""

# === 比赛设定 ===
FIELD_LENGTH = 14.0
FIELD_WIDTH = 10.0
GOAL_WIDTH = 1.0
GOAL_HALF = 0.5
BALL_RADIUS = 0.11
ROBOT_HEIGHT = 0.72
FALL_HEIGHT = 0.4

# === 踢球 ===
KICK_POWER_DEFAULT = 5.0
KICK_POWER_NEAR_GOAL = 4.5
KICK_POWER_CLEARANCE = 8.0
KICK_ENTER_M = 0.5
KICK_EXIT_M = 0.8
KICK_COOLDOWN_S = 0.5
KICK_IMPULSE = 3.0

# === 带球 ===
DRIBBLE_KICK_POWER = 2.0
DRIBBLE_ENTER_M = 0.5
DRIBBLE_EXIT_M = 0.7
DRIBBLE_SHOOT_RANGE_M = 4.0
DRIBBLE_MAX_SPEED = 1.2

# === 追球 ===
CHASE_BEHIND_M = 0.35
ATTACKER_KEEP_MARGIN_M = 0.3    # 防震荡
FALLEN_COST_M = 10.0            # 跌倒球员的距离惩罚

# === 角色与阵型 ===
GUARD_THREAT_ENTER_X = -1.0
GUARD_THREAT_EXIT_X = -0.7
GUARD_PRESS_X = -0.45
SUPPORT_FORWARD_M = 1.0
SUPPORT_WIDTH_M = 2.0
SUPPORT_CLEARANCE_M = 1.2

# === 传球 ===
PASS_ENABLED = True
PASS_POWER = 3.6
PASS_MAX_DIST_M = 3.2
PASS_MIN_FORWARD_M = 0.45
PASS_CLEARANCE_M = 1.0
PASS_LANE_CLEARANCE_M = 0.65

# === 反抢 ===
COUNTER_PRESS_ENABLED = True
COUNTER_PRESS_WINDOW_S = 2.5
COUNTER_PRESS_MAX_DIST_M = 4.0
POSSESSION_MARGIN_M = 0.5

# === 避障 ===
OPPONENT_RADIUS = 0.55
TEAMMATE_RADIUS = 0.48
BALL_OBSTACLE_RADIUS = 0.5
SAFETY_MARGIN = 0.22
PLAN_LOOKAHEAD = 1.2
PLAN_CLEARANCE = 0.35
PLAN_STEP_DEG = 15

# === Walk model ===
ACTION_SCALE = 0.25
HL_CLIP_LIN = 1.2
HL_CLIP_ANG = 1.2
DECIMATION = 5
